backend/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include, re_path
from django.views.generic import RedirectView

import yama.views as yama_views
from accounts.views import login_view, registration_view, forgot_password
from yama.decorators import check_recaptcha
from .views import about, faq, license

handler404 = 'yama.views.page404'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pits/', include('yama.urls')),
    path('about/', about, name="about"),
    path('faq/', faq, name="faq"),
    path('license/', license, name="user_license"),
    path('logout/', LogoutView.as_view(), name="logout"),
    # TODO: пофиксить на логин

    path('account/', include('django.contrib.auth.urls')),

    path('login/', login_view, name='login'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    # path('register/', registration_view, name='register'),
    path('register/', check_recaptcha(registration_view), name='register'),
    path('', yama_views.index, name="index")
]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += [
    #     path('favicon.ico', RedirectView.as_view(url=settings.STATIC_URL + 'favicon.ico'))
    # ]
else:
    import django.views.static

    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', django.views.static.serve,
                {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),
        re_path(r'^media/(?P<path>.*)$', django.views.static.serve,
                {'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}),
    ]

backend/yama/urls.py
from django.urls import path

import yama.views as views

urlpatterns = [
    path('', views.pit_list, name="pit_list"),
    path('maps/list/', views.map_pit_list, name="pit_map_list"),
    path('add/', views.pit_add, name="pit_add"),
    path('<pit_id>/', views.pit_detail, name="pit_detail"),
]

backend/yama/models.py
from django.contrib.auth import get_user_model
from django.db import models
from sorl.thumbnail import ImageField
User = get_user_model()


class Pit(models.Model):
    PIT_TYPE_CHOICES = (
        ('on_road', 'Яма на дороге'),
        ('on_yard', 'Яма во дворе')
    )

    latitude = models.CharField('Широта', max_length=30)
    longitude = models.CharField('Долгота', max_length=30)
    place_description = models.CharField('Описание расположения',
                                         max_length=100)
    city = models.CharField('Город', max_length=50)
    region = models.CharField('Регион', max_length=50)
    address = models.CharField('Полный адрес', max_length=300)

    pit_type = models.CharField('Тип повреждения', max_length=10,
                                choices=PIT_TYPE_CHOICES)
    pit_description = models.CharField('Описание повреждения', max_length=200)

    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                               blank=True)

    created = models.DateTimeField('Дата создания', auto_now=True,
                                   editable=False)
    edited = models.DateTimeField('Дата изменения', auto_now_add=True,
                                  editable=False)

    @property
    def status(self):
        return self.statuses.last()


class PitImage(models.Model):
    pit = models.ForeignKey(Pit, default=None, related_name='images',
                            on_delete=models.CASCADE)
    image = ImageField('Изображение', upload_to='static/uploads')


class PitStatus(models.Model):
    MODERATE = 'moderate'
    ON_POLICE = 'on_police'
    POLICE_DISCARD = 'police_discard'
    POLICE_NO_ANSWER = 'police_no_answer'
    ON_PLANE = 'on_plane'
    DONE = 'done'
    MODERATE_DISCARD = 'moderate_discard'
    DELETED = 'deleted'

    PIT_STATUS_CHOICES = (
        (MODERATE, 'На модерации'),
        (ON_POLICE, 'В полиции'),
        (POLICE_NO_ANSWER, 'Нет ответа от полиции'),
        (POLICE_DISCARD, 'Отказано полицией'),
        (ON_PLANE, 'Ремонт запланирован'),
        (MODERATE_DISCARD, 'Отказано модератором'),
        (DONE, 'Отремонтировано'),
        (DELETED, 'Удалено'),
    )

    pit = models.ForeignKey(Pit, default=None, related_name='statuses',
                            on_delete=models.CASCADE)
    status = models.CharField('Статус заявки', max_length=20,
                              choices=PIT_STATUS_CHOICES)
    created = models.DateTimeField('Дата создания', auto_now=True)

    def __str__(self):
        return dict(self.PIT_STATUS_CHOICES)[self.status]

backend/yama/forms.py
from django.forms import ModelForm
from django import forms

from yama.models import Pit


class PitForm(ModelForm):
    # latitude = forms
    # author = forms.CharField(widget=forms.HiddenInput())
    latitude = forms.CharField(widget=forms.HiddenInput())
    longitude = forms.CharField(widget=forms.HiddenInput())
    city = forms.CharField(widget=forms.HiddenInput())
    region = forms.CharField(widget=forms.HiddenInput())
    address = forms.CharField(widget=forms.HiddenInput())
    class Meta:
        model = Pit
        fields = ('latitude', 'longitude', 'place_description', 'city',
                  'region', 'address', 'pit_type', 'pit_description')

backend/yama/views.py
import json

from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from yama.forms import PitForm
from yama.models import Pit, PitStatus, PitImage
from yama.services import pit_maps, pit_pipeline
from yama.services.pit_pipeline import get_filtered_pits


def index(request) -> HttpResponse:
    print(request.GET.getlist('markers'))
    pits = get_filtered_pits(request)
    return render(request, 'yama/index.html', {
        'pits': pits,
        'map_pits': json.dumps(pit_maps.get_markers_for_map(pits))
    })


def pit_list(request) -> HttpResponse:
    pits = get_filtered_pits(request)
    paginator = Paginator(pits, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'yama/index.html', {'pits': pits,
                                               'page_obj': page_obj,
                                               'is_list': True})


def pit_detail(request, pit_id) -> HttpResponse:
    pit = Pit.objects.filter(pk=pit_id).first()
    if not pit_pipeline.pit_has_displayed(pit, request.user):
        return render(request, 'yama/404.html', status=404)
    context = {
        'pit': pit,
        'map_pits': json.dumps(pit_maps.get_markers_for_map([pit]))
    }
    return render(request, 'yama/pit-detail.html', context)


def pit_add(request) -> HttpResponse:
    if not request.user.is_authenticated:
        return redirect('index')
    pit_form = PitForm()
    if request.method == 'POST':
        pit_form = PitForm(request.POST)
        if pit_form.is_valid():
            result = pit_form.save()
            result.author = request.user
            result.save()
            for image in request.FILES.getlist('pit_image[]')[:5]:
                PitImage.objects.create(pit=result, image=image)
            return JsonResponse({
                'success': True,
                'pit_id': result.id
            })
        return JsonResponse({
            'success': False,
            'error': 'Проверьте правильность введенных данных, и укажите точку на карте'
        })
    return render(request, 'yama/pit-add.html', {'pit_form': pit_form})


def map_pit_list(request) -> HttpResponse:
    pits = get_filtered_pits(request)
    return JsonResponse(pit_maps.get_markers_for_map(pits))


def page404(request, exception) -> HttpResponse:
    return render(request, 'yama/404.html')

backend/yama/templates/yama/index.html
{% extends "base.html" %}
{% load get_list %}
{% load static active_link_tags %}


{% block title %}{% endblock %}

{% block extra_head %}
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru-RU&amp;apikey=9814077a-013e-4cc3-884c-b39c3dfa1168"
            type="text/javascript"></script>
    {% if not is_list %}

        <script type="application/javascript">
            ymaps.ready(init);

            function init() {
                var myMap = new ymaps.Map('map', {
                        center: [43.238293, 76.945465],
                        zoom: 12
                    }, {
                        autoFitToViewport: 'always',
                        searchControlProvider: 'yandex#search'
                    }),
                    objectManager = new ymaps.ObjectManager({
                        // Чтобы метки начали кластеризоваться, выставляем опцию.
                        clusterize: true,
                        // ObjectManager принимает те же опции, что и кластеризатор.
                        gridSize: 32,
                        clusterDisableClickZoom: true
                    });


                // Чтобы задать опции одиночным объектам и кластерам,
                // обратимся к дочерним коллекциям ObjectManager.
                objectManager.objects.options.set('preset', 'islands#redDotIcon');
                objectManager.clusters.options.set('preset', 'islands#redClusterIcons');
                myMap.geoObjects.add(objectManager);
                objectManager.add({{ map_pits | safe }})
                /* $.ajax({
                    url: "/pits/maps/list/"
                }).done(function (data) {
                    objectManager.add(data);
                }); */

            }
        </script>
    {% endif %}
    <style>
        #map {
            width: 100%;
            height: calc(100vh - 94px - 78px - 60px);
            padding: 0;
            margin: 0;
        }
    </style>


{% endblock %}
{% block content %}
    <div class="container">
        <div class="row py-4">
            <div class="col-xl-3 col-lg-4 col-md-5">
                {% include 'yama/ui/pit-filters.html' %}
            </div>


            <div class="col-lg-8 col-md-7 col-xl-9">
                <div class="shadow block d-flex justify-content-between mb-3 align-items-center">
                    <span class="founded-label">Найдено: <i>{{ pits.count }} ям</i></span>
                    <ul class="nav justify-content-end">

                        <li class="nav-item mr-2">
                            <a class="btn btn-lg change_vis_btn y-bg-gray {% active_link 'index' %}"
                               href="{% url 'index' %}?{{ request.GET.urlencode }}">
                                <i class="bi bi-map-fill"></i> Карта
                            </a>
                        </li>
                        <li class="nav-item mx-0">
                            <a class="btn change_vis_btn y-bg-gray {% active_link 'pit_list' %}"
                               href="{% url 'pit_list' %}?{{ request.GET.urlencode }}">
                                <i class="bi bi-grid-fill"></i> Список
                            </a>
                        </li>

                    </ul>
                </div>

                {% if not is_list %}
                    <div class="row mb-4">
                        <div class="col">
                        </div>

                        <div class="w-100"></div>
                        <div class="col">
                            <div class="map shadow">
                                <div id="map"></div>
                            </div>
                        </div>

                    </div>
                {% else %}
                    <div class="row">

                        {% for pit in page_obj %}
                            {% include 'yama/ui/pit-item.html' with pit=pit %}
                        {% endfor %}


                    </div>

                    <div class="pagination text-center">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo;</a>
                            <a href="?page={{ page_obj.previous_page_number }}"><</a>
                        {% endif %}

                        <div class="current mx-auto">
                            Страница {{ page_obj.number }}
                            из {{ page_obj.paginator.num_pages }}
                        </div>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">></a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                        {% endif %}
                    </div>

                {% endif %}

            </div>

        </div>
    </div>

{% endblock %}

backend/yama/templates/yama/pit-add.html
{% extends "base.html" %}

{% block title %}Добавление ямы -{% endblock %}

{% block extra_head %}
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru-RU&amp;apikey=9814077a-013e-4cc3-884c-b39c3dfa1168"
            type="text/javascript"></script>

    <script type="application/javascript">
        ymaps.ready(init);

        function init() {
            var myPlacemark;
            var myMap = new ymaps.Map('map', {
                center: [43.238293, 76.945465],
                zoom: 12
            }, {
                autoFitToViewport: 'always',
                searchControlProvider: 'yandex#search'
            });

            myMap.events.add('click', function (e) {
                var coords = e.get('coords');
                // Если метка уже создана – просто передвигаем ее.
                if (myPlacemark) {
                    myPlacemark.geometry.setCoordinates(coords);
                }
                // Если нет – создаем.
                else {
                    myPlacemark = createPlacemark(coords);
                    myMap.geoObjects.add(myPlacemark);
                    // Слушаем событие окончания перетаскивания на метке.
                    myPlacemark.events.add('dragend', function () {
                        getAddress(myPlacemark.geometry.getCoordinates());
                    });
                }
                getAddress(coords);
            });

            // Создание метки.
            function createPlacemark(coords) {
                return new ymaps.Placemark(coords, {
                    iconCaption: 'поиск...'
                }, {
                    preset: 'islands#redDotIconWithCaption',
                    draggable: true
                });
            }

            // Определяем адрес по координатам (обратное геокодирование).
            function getAddress(coords) {
                $('#id_latitude').val(coords[0]);
                $('#id_longitude').val(coords[1]);
                console.log(coords);
                myPlacemark.properties.set('iconCaption', 'поиск...');
                ymaps.geocode(coords).then(function (res) {
                    var firstGeoObject = res.geoObjects.get(0);

                    console.log(firstGeoObject.getAdministrativeAreas());
                    $('#id_city').val(firstGeoObject.getLocalities()[0]);
                    $('#id_region').val(firstGeoObject.getAdministrativeAreas()[0]);
                    $('#id_address').val(firstGeoObject.getAddressLine());
                    $('#addressText').text(firstGeoObject.getAddressLine());

                    myPlacemark.properties
                        .set({
                            // Формируем строку с данными об объекте.
                            iconCaption: [
                                // Название населенного пункта или вышестоящее административно-территориальное образование.
                                firstGeoObject.getLocalities().length ? firstGeoObject.getLocalities() : firstGeoObject.getAdministrativeAreas(),
                                // Получаем путь до топонима, если метод вернул null, запрашиваем наименование здания.
                                firstGeoObject.getThoroughfare() || firstGeoObject.getPremise()
                            ].filter(Boolean).join(', '),
                            // В качестве контента балуна задаем строку с адресом объекта.
                            balloonContent: firstGeoObject.getAddressLine()
                        });
                });
            }
        }
    </script>

    <style>
        #map {
            width: 100%;
            height: calc(450px);
            padding: 0;
            margin: 0;
        }
    </style>


{% endblock %}

{% block content %}
    <style>
        .downloadedPhotos {
            width: 100px;
            height: 100px;
            overflow: hidden;
        }

        .downloadedPhotos img {
            width: 100%;
            height: auto;
        }
    </style>
    <div class="container py-5">
        <div class="row">
            <div class="col-md-8">
                <h3>Добавление ямы</h3>


                <form id="addPitForm" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="hidden" name="latitude" id="id_latitude">
                    <input type="hidden" name="longitude" id="id_longitude">
                    <input type="hidden" name="city" id="id_city">
                    <input type="hidden" name="region" id="id_region">
                    <input type="hidden" name="address" id="id_address">

                    <h5>Укажите местоположение ямы на карте</h5>
                    <div id="map"></div>

                    <p id="addressText" class="text-secondary mt-3"></p>
                    <div class="mb-3">
                        <textarea type="text" class="form-control"
                                  maxlength="100"
                                  name="place_description" autocomplete="off"
                                  placeholder="Описание расположения"></textarea>
                    </div>

                    <h5>Опишите тип повреждения</h5>
                    <div class="mb-3">
                        <select class="form-select" name="pit_type">
                            <option value="">Выберите тип</option>
                            <option value="on_road">Яма на дороге</option>
                            <option value="on_yard">Яма во дворе</option>
                        </select>
                    </div>

                    <div class="mb-3">
                        <textarea type="text" class="form-control"
                                  name="pit_description" autocomplete="off"
                                  placeholder="Оставьте комментарий к тексту обращения"
                                  maxlength="200"></textarea>
                    </div>

                    <h5>Загрузите фотографии ямы</h5>
                    <div id="photos" class="row"></div>

                    <input type='file' id="imgInp" name="pit_image[]" multiple/>
                    <p class="text-secondary">Можно загружать до пяти
                        фотографий</p>

                    <p class="errors text-danger text-center"
                       style="font-size: 0.8em;"></p>

                    <button type="submit"
                            class="btn btn-danger w-100">
                        Добавить
                    </button>


                </form>
            </div>


            <div class="col-md-4 mt-3 mt-md-0">
                <h4>Добавление ямы</h4>
                <p>
                    1. После добавления ямы модератор проверит обращение и
                    отправит
                    его через интернет-приёмную на сайте Акимата Алматы.
                    {#                    Там требуются#}
                    {#                    данные#}
                    {#                    заявителя, поэтому мы спрашиваем ваши имя и фамилию при#}
                    {#                    регистрации. #}
                    Нам нужен email — чтобы переслать вам ответ
                </p>
                <p>
                    2.
                    {#                    Региональное управление  получит обращение и#}
                    {#                    переправит#}
                    {#                    его в нужный территориальный отдел.#}
                    Сотрудники отдела выедут на проверку ямы
                </p>
                <p>
                    3. Акимат выдаст предписание на ремонт
                    {#                    3. Если яма превышает допустимые размеры, то отдел #}
                    {#                    установит ответственного, заведет административное дело и#}
                    {#                    выдаст#}
                    {#                    предписание на ремонт#}
                </p>
                <p>
                    4. Подрядчик должен исполнить предписание.
                    {#                    в течение 12 дней.#}
                    Если он этого не сделает, мы отправим повторное обращение в
                    Акимат Алматы и попросим проверить исполнение
                </p>
                {#                <p>#}
                {#                    5. В этой ситуации поможет жалоба в региональную#}
                {#                    прокуратуру,#}
                {#                    которая должна проверить, почему предписание не выполнено, и#}
                {#                    обязать подрядчика сделать ремонт#}
                {#                </p>#}
            </div>
        </div>
    </div>






    <script>
        {% if user.is_authenticated %}
            var photos;
            $('#addPitForm').submit(function (e) {

                $.ajax({
                    type: "POST",
                    url: '{% url 'pit_add' %}',
                    data: new FormData(this),
                    processData: false,
                    contentType: false,
                    success: function (response) {
                        if (response['success']) {
                            document.location.href = '/pits/' + response['pit_id'] + '/';
                        } else {
                            $('#addPitForm .errors').text(response['error']);
                        }

                    }
                });
                e.preventDefault();
            });

            function readURL(input) {
                for (file of input.files) {
                    if (file) {
                        var reader = new FileReader();

                        reader.onload = function (e) {
                            $('#photos').html($('#photos').html() + `<div class="downloadedPhotos"><img src="${e.target.result}" alt="downloading image" /></div>`);
                        }
                        reader.readAsDataURL(file); // convert to base64 string

                    }
                }
            }

            $("#imgInp").change(function () {
                $('#photos').html('');
                readURL(this);
            });
        {% endif %}
    </script>

{% endblock %}

backend/yama/templates/yama/pit-list.html
{% extends "base.html" %}


{% block title %}{% endblock %}

{% block content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-md-3">
                {% include 'yama/ui/pit-filters.html' %}
            </div>
            <div class="col-md-9">
                <div class="row">
                    {% for pit in page_obj %}
                        {% include 'yama/ui/pit-item.html' with pit=pit %}
                    {% endfor %}
                </div>

                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>

    </div>
{% endblock %}